language: cpp
sudo: false
dist: trusty
compiler:
- clang++
os:
- linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main'
        packages:
            - lcov
#            - libglfw3
#            - libglfw3-dev
            - ninja-build
            - xorg-dev
            - libglu1-mesa-dev
            - apt-transport-https
            - libunwind-dev

branches:
  only:
  - master

before_install:
    - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
    - sudo dpkg -i packages-microsoft-prod.deb
    - sudo apt-get update
    - sudo apt-get install dotnet-sdk-2.1

script:
   - cd CodekraftBuildTool
   - ./build-and-install.sh
   - cd ..
   - ckb -i engine/
   - ckb testgame/

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

env:
  global:
  - LANG="en_US.UTF-8"
