language: cpp
sudo: false
dist: trusty
compiler:
- g++
os:
- linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main'
        packages:
            - lcov
            - libglfw3
            - libglfw3-dev

branches:
  only:
  - master

#before_install:

script:
   - mkdir build
   - cd build
   - cmake ..
   - make -j$(nproc)

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

env:
  global:
  - LANG="en_US.UTF-8"
