#!/bin/bash

CLEAN=0
RUN="no"

if [ echo ${PWD##*/} == "scripts" ]; then
    cd ..
fi

if [ $# -gt 0 ]; then
    if [ $1 == "clean" ]; then
        CLEAN=1
        if [ $# -lt 2 ]; then
            RUN="no"
        else
            RUN=$2
        fi
    else
        CLEAN=0
        if [ $# -lt 1 ]; then
            RUN="no"
        else
            RUN=$1
        fi
    fi
else
    RUN="no"
    CLEAN=0
fi

cd build
cmake ..
if [ $CLEAN -eq 1 ]; then
    make clean
fi
make all -j6
if [ $RUN == "run" ]; then
    cd testgame
    ./TestGame
fi